"""File um UUID erweitert

Revision ID: 57729dd71bde
Revises: 75d54c556f4d
Create Date: 2026-07-13 13:29:51.329827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57729dd71bde'
down_revision = '75d54c556f4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('file_uuid'))
        batch_op.create_index(batch_op.f('ix_files_file_uuid'), ['file_uuid'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_file_uuid'))
        batch_op.create_index(batch_op.f('file_uuid'), ['file_uuid'], unique=True)

    # ### end Alembic commands ###
