"""abg and dsgvo added to User table

Revision ID: 6d063073d90f
Revises: f06c1e3941ec
Create Date: 2026-08-25 08:32:46.669382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d063073d90f'
down_revision = 'f06c1e3941ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dsgvo_accepted', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('agb_accepted', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('agb_accepted')
        batch_op.drop_column('dsgvo_accepted')

    # ### end Alembic commands ###
