"""File um UUID erweitert

Revision ID: 75d54c556f4d
Revises: e0cc6c485a75
Create Date: 2026-07-13 13:25:27.740506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75d54c556f4d'
down_revision = 'e0cc6c485a75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_uuid', sa.String(length=36), nullable=False))
        batch_op.create_unique_constraint(None, ['file_uuid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('file_uuid')

    # ### end Alembic commands ###
