"""Tabellen anpassungen

Revision ID: f06c1e3941ec
Revises: 57729dd71bde
Create Date: 2026-07-21 12:40:21.653804

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f06c1e3941ec'
down_revision = '57729dd71bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('original_filename',
               existing_type=mysql.VARCHAR(length=155),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('storage_filename',
               existing_type=mysql.VARCHAR(length=155),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('file_size',
               existing_type=mysql.INTEGER(display_width=11),
               type_=sa.BigInteger(),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('file_size',
               existing_type=sa.BigInteger(),
               type_=mysql.INTEGER(display_width=11),
               existing_nullable=False)
        batch_op.alter_column('storage_filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=155),
               existing_nullable=False)
        batch_op.alter_column('original_filename',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=155),
               existing_nullable=False)

    # ### end Alembic commands ###
